#==========================================================================
# Description: Build Armbian
# Copyright (C) 2023 https://github.com/windbell-project/msm8916-armbian
#==========================================================================
name: Rebuild armbian.som3588
 ，缪缪有，0
on:
  workflow_dispatch:
    inputs:
      armbian_board:
        description: "选择设备"
        required: true
        default: "som3588"
        type: choice
        options:
          - som3588

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 安装依赖
        run: |
          sudo apt update -y
          sudo apt-get -y install git
      - name: 下载源码
        run: |
          git clone --depth=1 --branch=main https://github.com/YANXIAOXIH/build
      - name: 下载镜像
        run: |
          pushd build
          ./compile.sh build BOARD=som3588-cat BRANCH=vendor BUILD_DESKTOP=no BUILD_MINIMAL=yes KERNEL_CONFIGURE=no RELEASE=bookworm
          popd
      - name: 上传 Armbian 镜像至 Release
        uses: ncipollo/release-action@main
        with:
          artifacts: "*/*/*.img"
          name: ${{ steps.repack.outputs.build_tag }}
          tag: ${{ steps.repack.outputs.build_tag }}
          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ### 以下是 Armbian OS 镜像
            - 本次固件基带为${{ inputs.armbian_board }}
            - 系统信息：
            - 默认用户名：root
            - 默认密码：1234
            - 全局配置命令：armbian-config
            - WiFi名称：4G-UFI
            - WiFi密码：12345678
            - 如遇无法开机的情况请使用未超频内核boot-no-overclock.img
